import type { NextApiRequest, NextApiResponse } from "next";
import { getSupabaseAdmin } from "@/lib/supabaseServer";
import { normalizeRoleInterviewReport } from "@/lib/careers/types";
import { renderRoleInterviewReportPdf } from "@/lib/reports/renderRoleInterviewReportPdf";
import { getResendFromAddress, getReplyToEmail } from "@/lib/email/resendClient";
import { findRoleReportRow } from "@/lib/careers/roleReportLookup";

// Pages Router — see src/pages/api/careers/interview/report/email.ts for why
// (@react-pdf/renderer crashes inside the App Router).
// Emails the role hiring summary PDF (whichever version is current) to an
// address HR provides.
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    return res.status(405).json({ error: "Method not allowed" });
  }

  const supabaseAdmin = getSupabaseAdmin();
  if (!supabaseAdmin) {
    return res.status(500).json({ error: "Server configuration error" });
  }
  if (!process.env.RESEND_API_KEY) {
    return res.status(500).json({ error: "RESEND_API_KEY is not configured" });
  }

  try {
    const { job_posting_id, role_slug, to } = req.body ?? {};
    if ((!job_posting_id && !role_slug) || !to) {
      return res.status(400).json({ error: "job_posting_id (or role_slug) and to are required." });
    }

    const { data, error: fetchError } = await findRoleReportRow(supabaseAdmin, {
      jobPostingId: job_posting_id ?? null,
      roleSlug: role_slug ?? null,
    });

    if (fetchError || !data) {
      return res.status(404).json({ error: fetchError?.message ?? "No report found for this hiring round." });
    }

    const row = data;
    const report = normalizeRoleInterviewReport(row.report_edit ?? row.report);

    const pdfBuffer = await renderRoleInterviewReportPdf(report);
    const fileName = `role-hiring-summary-${row.role_title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.pdf`;

    const { Resend } = await import("resend");
    const resend = new Resend(process.env.RESEND_API_KEY);

    const { error } = await resend.emails.send({
      from: getResendFromAddress("Wills Farms Careers"),
      to,
      replyTo: getReplyToEmail(),
      subject: `Role hiring summary — ${row.role_title}`,
      html: `
        <div style="font-family: Arial, sans-serif; color: #333; line-height: 1.5; max-width: 560px;">
          <h2 style="color: #b91c1c;">Role Hiring Summary</h2>
          <p><strong>Role:</strong> ${row.role_title}</p>
          <p>The full hiring summary report is attached as a PDF.</p>
          <p style="font-size:12px;color:#999;margin-top:24px;">Generated by Wills Farms Human Capital on ${new Date().toLocaleString("en-GB")}.</p>
        </div>
      `,
      text: `Role hiring summary for ${row.role_title} is attached.`,
      attachments: [
        {
          filename: fileName,
          content: pdfBuffer.toString("base64"),
        },
      ],
    });

    if (error) {
      return res.status(502).json({ error: error.message });
    }

    return res.status(200).json({ success: true });
  } catch (err) {
    console.error("[POST /api/careers/interview/role-report/email]", err);
    return res.status(500).json({ error: "Server error" });
  }
}
