import { NextRequest, NextResponse } from "next/server";
import { getSupabaseAdmin } from "@/lib/supabaseServer";
import { normalizeInterviewFormData } from "@/lib/careers/types";
import { renderInterviewReportPdf } from "@/lib/reports/renderInterviewReportPdf";
import { getResendFromAddress, getReplyToEmail } from "@/lib/email/resendClient";

// Emails the interview report PDF (whichever version is current) to an
// address HR provides.
export async function POST(req: NextRequest) {
  const supabaseAdmin = getSupabaseAdmin();
  if (!supabaseAdmin) {
    return NextResponse.json({ error: "Server configuration error" }, { status: 500 });
  }
  if (!process.env.RESEND_API_KEY) {
    return NextResponse.json({ error: "RESEND_API_KEY is not configured" }, { status: 500 });
  }

  try {
    const { application_id, to } = (await req.json()) as {
      application_id?: string;
      to?: string;
    };

    if (!application_id || !to) {
      return NextResponse.json(
        { error: "application_id and to are required." },
        { status: 400 },
      );
    }

    const { data: application, error: fetchError } = await supabaseAdmin
      .from("job_applications")
      .select("full_name, role_title, reference_number, interview_form_data")
      .eq("id", application_id)
      .single();

    if (fetchError || !application) {
      return NextResponse.json(
        { error: fetchError?.message ?? "Application not found." },
        { status: 404 },
      );
    }

    const formData = normalizeInterviewFormData(application.interview_form_data);
    const report = formData.summary?.interview_report_edit ?? formData.summary?.interview_report;

    if (!report) {
      return NextResponse.json(
        { error: "No interview report has been generated for this applicant yet." },
        { status: 400 },
      );
    }

    const pdfBuffer = await renderInterviewReportPdf(report);
    const fileName = `interview-report-${application.full_name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.pdf`;

    const { Resend } = await import("resend");
    const resend = new Resend(process.env.RESEND_API_KEY);

    const { error } = await resend.emails.send({
      from: getResendFromAddress("Wills Farms Careers"),
      to,
      replyTo: getReplyToEmail(),
      subject: `Interview report — ${application.full_name} (${application.role_title})`,
      html: `
        <div style="font-family: Arial, sans-serif; color: #333; line-height: 1.5; max-width: 560px;">
          <h2 style="color: #b91c1c;">Interview Report</h2>
          <p><strong>Candidate:</strong> ${application.full_name}</p>
          <p><strong>Role:</strong> ${application.role_title}</p>
          <p><strong>Reference:</strong> ${application.reference_number}</p>
          <p>The full interview report is attached as a PDF.</p>
          <p style="font-size:12px;color:#999;margin-top:24px;">Generated by Wills Farms Human Capital on ${new Date().toLocaleString("en-GB")}.</p>
        </div>
      `,
      text: `Interview report for ${application.full_name} (${application.role_title}, ref ${application.reference_number}) is attached.`,
      attachments: [
        {
          filename: fileName,
          content: pdfBuffer.toString("base64"),
        },
      ],
    });

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 502 });
    }

    return NextResponse.json({ success: true });
  } catch (err) {
    console.error("[POST /api/careers/interview/report/email]", err);
    return NextResponse.json({ error: "Server error" }, { status: 500 });
  }
}
