import type { NextApiRequest, NextApiResponse } from "next";
import { getSupabaseAdmin } from "@/lib/supabaseServer";
import { normalizeInterviewFormData } from "@/lib/careers/types";
import { renderInterviewReportPdf } from "@/lib/reports/renderInterviewReportPdf";
import { getResendFromAddress, getReplyToEmail } from "@/lib/email/resendClient";

// This lives in the Pages Router (src/pages/api/...) rather than the App
// Router, for the same reason as src/pages/api/task-manager/reports/send.tsx:
// @react-pdf/renderer's renderToBuffer() crashes with "Minified React error
// #31" specifically inside Next's App Router request handling (unresolved
// upstream issue — see https://github.com/diegomura/react-pdf/issues/2994).
// Emails the interview report PDF to an address HR provides. If HR has
// saved an edited copy, both the AI-generated original and the edited
// version go out as two attachments on the same email; otherwise just the
// single AI-generated PDF is attached.
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    return res.status(405).json({ error: "Method not allowed" });
  }

  const supabaseAdmin = getSupabaseAdmin();
  if (!supabaseAdmin) {
    return res.status(500).json({ error: "Server configuration error" });
  }
  if (!process.env.RESEND_API_KEY) {
    return res.status(500).json({ error: "RESEND_API_KEY is not configured" });
  }

  try {
    const { application_id, to } = req.body ?? {};
    if (!application_id || !to) {
      return res.status(400).json({ error: "application_id and to are required." });
    }

    const { data: application, error: fetchError } = await supabaseAdmin
      .from("job_applications")
      .select("full_name, role_title, reference_number, interview_form_data")
      .eq("id", application_id)
      .single();

    if (fetchError || !application) {
      return res.status(404).json({ error: fetchError?.message ?? "Application not found." });
    }

    const formData = normalizeInterviewFormData(application.interview_form_data);
    const aiReport = formData.summary?.interview_report;
    const editedReport = formData.summary?.interview_report_edit;
    const report = editedReport ?? aiReport;

    if (!report) {
      return res.status(400).json({ error: "No interview report has been generated for this applicant yet." });
    }

    const baseFileName = `interview-report-${application.full_name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}`;
    const hasBothCopies = !!(aiReport && editedReport);

    const attachments = hasBothCopies
      ? await Promise.all([
          renderInterviewReportPdf(aiReport!).then((buffer) => ({
            filename: `${baseFileName}-ai-generated.pdf`,
            content: buffer.toString("base64"),
          })),
          renderInterviewReportPdf(editedReport!).then((buffer) => ({
            filename: `${baseFileName}-edited.pdf`,
            content: buffer.toString("base64"),
          })),
        ])
      : [
          {
            filename: `${baseFileName}.pdf`,
            content: (await renderInterviewReportPdf(report)).toString("base64"),
          },
        ];

    const { Resend } = await import("resend");
    const resend = new Resend(process.env.RESEND_API_KEY);

    const { error } = await resend.emails.send({
      from: getResendFromAddress("Wills Farms Careers"),
      to,
      replyTo: getReplyToEmail(),
      subject: `Interview report — ${application.full_name} (${application.role_title})`,
      html: `
        <div style="font-family: Arial, sans-serif; color: #333; line-height: 1.5; max-width: 560px;">
          <h2 style="color: #b91c1c;">Interview Report</h2>
          <p><strong>Candidate:</strong> ${application.full_name}</p>
          <p><strong>Role:</strong> ${application.role_title}</p>
          <p><strong>Reference:</strong> ${application.reference_number}</p>
          <p>
            ${
              hasBothCopies
                ? "Both the AI-generated report and HR's edited version are attached as PDFs."
                : "The full interview report is attached as a PDF."
            }
          </p>
          <p style="font-size:12px;color:#999;margin-top:24px;">Generated by Wills Farms Human Capital on ${new Date().toLocaleString("en-GB")}.</p>
        </div>
      `,
      text: hasBothCopies
        ? `Interview report for ${application.full_name} (${application.role_title}, ref ${application.reference_number}) is attached — both the AI-generated version and HR's edited version.`
        : `Interview report for ${application.full_name} (${application.role_title}, ref ${application.reference_number}) is attached.`,
      attachments,
    });

    if (error) {
      return res.status(502).json({ error: error.message });
    }

    return res.status(200).json({ success: true });
  } catch (err) {
    console.error("[POST /api/careers/interview/report/email]", err);
    return res.status(500).json({ error: "Server error" });
  }
}
