-- ============================================================================
-- current_database_schema.sql
--
-- REVERSE-ENGINEERED snapshot of the willis-farms application's database
-- structure, as it exists TODAY — not a redesign, not an idealized schema.
-- Generated by inspecting the entire codebase: there is no ORM (no Prisma /
-- TypeORM / Drizzle) — the app talks to Postgres directly through the
-- Supabase JS client. There is also no formal migrations folder; instead
-- there are ~150 manually-run, checked-in SQL files scattered under
-- docs/**/*.sql (each headed "Run once in the Supabase SQL editor"), which
-- served as the primary source for this file, cross-checked against
-- TypeScript types and actual .select()/.insert()/.update() calls in
-- src/app/api/** wherever no SQL doc existed or a doc looked stale.
--
-- Engine: PostgreSQL (via Supabase). Access layer: @supabase/supabase-js,
-- called directly — no ORM/query-builder abstraction.
--
-- IMPORTANT KNOWN GAP IN THE SOURCE MATERIAL: this reverse-engineering
-- effort already caught the checked-in docs being WRONG in two confirmed
-- cases:
--   1. sites.id was recently migrated from uuid to integer (see
--      docs/organizational-structure/migrate-site-id-to-numeric.sql, run
--      this session) — every FK column pointing at sites(id) across the
--      whole database follows suit. The original per-table docs for
--      appraisal_grade_templates, skill_log_templates, job_postings, and
--      users still show `site_id uuid` — WRONG, corrected below.
--   2. content.id (the SOP table) was assumed uuid in
--      docs/task-manager/supporting-tables.sql, but is actually bigint in
--      the live database — confirmed by a later doc
--      (docs/sop/sop-audit-log-fix-content-id-type.sql) that had to fix
--      sop_audit_log.content_id after inserts failed. Corrected below.
-- Given these two confirmed mismatches, treat every REVIEW REQUIRED marker
-- below as a real possibility that this script doesn't perfectly match the
-- live database, not a formality — please diff this against the actual
-- Supabase schema before relying on it.
--
-- Order below respects foreign-key dependencies (parents before children).
-- ============================================================================

-- REVIEW REQUIRED: assumed enabled (gen_random_uuid() is used everywhere);
-- not confirmed by any doc, since it's normally a one-time Supabase project
-- default rather than something the app's own docs would re-declare.
create extension if not exists pgcrypto;


-- ============================================================================
-- SECTION 1 — Organizational structure: fixed catalogs
-- ============================================================================

-- sites.id is INTEGER, not uuid — migrated this session (see header note).
-- Numbered starting at 101, auto-incrementing via sites_id_seq for new rows.
create sequence if not exists sites_id_seq;

create table if not exists sites (
  id integer primary key default nextval('sites_id_seq'),
  label text not null,
  code text not null unique,
  region text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter sequence sites_id_seq owned by sites.id;
create index if not exists sites_is_active_sort_order_idx on sites (is_active, sort_order);
-- trigger sites_set_updated_at before update -> set_updated_at()  -- REVIEW REQUIRED: exact trigger function body not located, assumed generic "set updated_at = now()"

create table if not exists business_units (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  code text not null unique,
  sort_order int not null default 0,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists business_units_is_active_sort_order_idx on business_units (is_active, sort_order);

create table if not exists departments (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  code text not null unique,
  sort_order int not null default 0,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists departments_is_active_sort_order_idx on departments (is_active, sort_order);

create table if not exists sections (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  code text not null unique,
  sort_order int not null default 0,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists sections_is_active_sort_order_idx on sections (is_active, sort_order);

create table if not exists grade_levels (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  code text not null unique,
  sort_order int not null default 0,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  rank int not null default 0,
  role_kind text not null default 'ranked' check (role_kind in ('ranked', 'consultant'))
  -- age_min / age_max existed briefly, then were dropped
  -- (docs/organizational-structure/drop-grade-levels-age-columns.sql) — not included here.
);
create index if not exists grade_levels_role_kind_rank_idx on grade_levels (role_kind, rank);


-- ============================================================================
-- SECTION 2 — Organizational structure: custom/dynamic lists
-- ============================================================================

create table if not exists org_custom_list_types (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  singular text not null,
  code text not null unique,
  has_region boolean not null default false,
  fields jsonb not null default '[]'::jsonb,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  table_name text not null unique,
  is_active boolean not null default true,
  is_numeric_range boolean not null default false,
  numeric_range_mode text not null default 'digits',   -- REVIEW REQUIRED: CHECK constraint values not fully confirmed; observed 'digits' | 'bands'
  job_posting_column text,
  job_posting_min_column text,
  job_posting_max_column text
);

-- REVIEW REQUIRED: custom_<slug> tables (e.g. custom_position, custom_age,
-- custom_salary, and any admin-created list) are generated dynamically at
-- runtime by a create_org_dynamic_list_table() Postgres function, per the
-- fields[] the admin configured for that list in org_custom_list_types.
-- Because the exact set of these tables and their extra columns is
-- runtime/admin-driven, it cannot be reconstructed as a fixed list of
-- CREATE TABLE statements from static code alone — inventing one here
-- would misrepresent what's actually in the database. The SHAPE every one
-- of them follows is:
--
--   create table custom_<slug> (
--     id uuid primary key default gen_random_uuid(),
--     label text not null,
--     code text not null unique,
--     region text,                          -- only if that list has_region
--     <admin-defined columns...>,           -- one per fields[] entry (text/numeric/boolean/date)
--     sort_order int not null default 0,
--     is_active boolean not null default true,
--     notes text,
--     created_at timestamptz not null default now(),
--     updated_at timestamptz not null default now()
--   );
--   create index <slug>_active_sort_idx on custom_<slug> (is_active, sort_order);
--
-- To get the actual current set of these tables and their real columns,
-- query information_schema directly against the live database, or read
-- org_custom_list_types.fields per row.


-- ============================================================================
-- SECTION 3 — Access control / Users
-- ============================================================================

-- REVIEW REQUIRED: no base CREATE TABLE for `users` exists anywhere in the
-- checked-in docs — every doc found is an ALTER TABLE against an
-- already-existing table, meaning this table predates the checked-in-SQL
-- convention entirely. The definition below is reconstructed from every
-- ALTER found plus src/types.ts; treat the base/legacy columns (id,
-- user_id, email, phone, role, first_name, last_name, company_id,
-- job_position) with lower confidence than the clearly-documented
-- access-control and org-placement columns.
create table if not exists users (
  id uuid primary key default gen_random_uuid(),      -- REVIEW REQUIRED: relationship between `id` and `user_id` (below) is not documented anywhere found
  user_id uuid not null unique,                         -- REVIEW REQUIRED: appears to be the Supabase auth.users.id this row corresponds to; compared to auth.uid() in RLS policies
  email text,
  phone text,
  role text,                                            -- legacy: 'employee' | 'manager' | 'admin' | 'super_admin' — superseded in practice by user_role_id below, per migration comment; REVIEW REQUIRED whether still written to
  first_name text,
  last_name text,
  company_id text,                                      -- REVIEW REQUIRED: type/source only found in a non-SQL doc (PLATFORM_AUDIT_AND_ROADMAP.md), not a .sql file
  job_position text,                                    -- free-text, largely superseded by structured org placement below
  grade_level text,                                     -- REVIEW REQUIRED: docs/organizational-structure/drop-users-grade-level-column.sql drops this column, but src/types.ts still declares it — cannot confirm from docs alone whether the drop actually ran against the live database
  final_score numeric,                                  -- REVIEW REQUIRED: type inferred, no SQL doc found; used in promotion-eligibility computation
  final_score_year int,                                 -- REVIEW REQUIRED: same as above
  promotion_eligible boolean,                            -- REVIEW REQUIRED: same as above

  -- Access control (docs/access-control/*.sql — high confidence)
  access_tier text not null default 'standard' check (access_tier in ('standard', 'delegated')),
  page_permissions jsonb not null default '[]'::jsonb,               -- legacy flat list of page keys
  page_permission_levels jsonb not null default '{}'::jsonb,         -- legacy { pageKey: "view"|"add"|"edit" }
  page_permission_actions jsonb not null default '{}'::jsonb,        -- current matrix { pageKey: { view/add/edit/approve/review: boolean } }
  access_updated_at timestamptz,
  access_updated_by uuid,
  is_disabled boolean not null default false,
  created_by uuid,
  email_verified boolean,                                -- REVIEW REQUIRED: doc notes a possible legacy text->boolean conversion; current type not fully certain
  email_confirm boolean,                                 -- REVIEW REQUIRED: same

  -- Recruitment/employment tracking (docs/careers/employee_tracking.sql)
  application_id uuid references job_applications(id) on delete set null,   -- NOTE: forward reference — job_applications is created in Section 8 below; if running this script top-to-bottom in one transaction this is fine (all tables exist before any data/constraint is used), but if running section-by-section, create this FK after job_applications exists
  employment_status text check (employment_status in ('probation', 'active', 'fired', 'quit', 'deceased')),
  platform_invited_at timestamptz,

  -- Org placement (docs/access-control/users-org-placement.sql +
  -- users-org-placement-user-role.sql — high confidence on shape, site_id
  -- type corrected per the migration noted in the file header)
  supervisor_id uuid references users(user_id) on delete set null,
  site_id integer references sites(id) on delete set null,             -- corrected: was uuid, migrated to integer this session
  business_unit_id uuid references business_units(id) on delete set null,
  department_id uuid references departments(id) on delete set null,
  section_id uuid references sections(id) on delete set null,
  position_id uuid references custom_position(id) on delete set null,  -- REVIEW REQUIRED: custom_position is a dynamically-generated table (see Section 2) — assumed to exist by convention, not verified as physically present under that exact name
  grade_level_id uuid references grade_levels(id) on delete set null,
  user_role_id uuid,                                                    -- REVIEW REQUIRED: references whichever custom_<slug> table is registered as the "User role" list — table name is resolved dynamically by the app, not a fixed FK target, so no `references` clause can be written statically here

  -- Task Manager scope (docs/task-manager/permissions.sql)
  tm_can_view_all_tasks boolean,

  created_at timestamptz not null default now()          -- REVIEW REQUIRED: existence/default not directly confirmed for this table, assumed for consistency with every other table in the codebase
);
create index if not exists users_access_tier_idx on users (access_tier);
create index if not exists users_supervisor_id_idx on users (supervisor_id);
-- REVIEW REQUIRED: users_grade_level_check (grade in L1..L7) existed then was
-- dropped (docs/access-control/users-grade-level-check.sql) — not included.
-- REVIEW REQUIRED: section_label and user_role_label seen on the TS User
-- type are explicitly NOT real columns per their own code comments — they
-- are computed/attached server-side on read. Not included here.


-- ============================================================================
-- SECTION 4 — System definitions
-- ============================================================================

create table if not exists system_modules (
  module_id text primary key,
  source text not null default 'override' check (source in ('override', 'dynamic')),
  form_definition jsonb,
  list_view jsonb,
  business_logic jsonb,          -- includes companyBranding {logoUrl, logoPublicId, addressLines} for offer letters — no dedicated table for that feature
  option_lists jsonb,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);
-- trigger system_modules_set_updated_at before update -> set_updated_at()

create table if not exists system_options (
  id text primary key,
  module_id text not null,
  option_list text not null,
  label text not null,
  legacy_value text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  rules jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint system_options_module_list_legacy_unique unique (module_id, option_list, legacy_value)
);
create index if not exists system_options_module_list_idx on system_options (module_id, option_list, is_active, sort_order);


-- ============================================================================
-- SECTION 5 — Permission presets / Access Control admin config
-- ============================================================================

create table if not exists access_group_presets (
  group_key text primary key check (group_key in (
    'standard_role', 'executive_role', 'human_resource',
    'supervisory_role', 'system_administrator', 'consultant', 'super_admin'
  )),
  page_permission_actions jsonb not null default '{}'::jsonb,
  updated_at timestamptz,
  updated_by uuid
);
-- REVIEW REQUIRED: an older 5-key version of this table's CHECK constraint
-- (employees/managers/admins/grade_l1_l3/grade_l4_l7) is described in
-- ACCESS_CONTROL_SUPABASE.md, but a newer migration (group-presets.sql)
-- replaces it with the 7-role keys above. Old rows under the retired keys
-- may still physically exist (harmless, unread by the app).

create table if not exists access_control_items (
  id uuid primary key default gen_random_uuid(),
  sidebar_item text not null,
  sidebar_submenu_item text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists access_control_items_unique_flat_idx
  on access_control_items (sidebar_item) where sidebar_submenu_item is null;
create unique index if not exists access_control_items_unique_submenu_idx
  on access_control_items (sidebar_item, sidebar_submenu_item) where sidebar_submenu_item is not null;

create table if not exists access_control_item_actions (
  id uuid primary key default gen_random_uuid(),
  access_control_item_id uuid not null references access_control_items(id) on delete cascade,
  action_label text not null,
  created_at timestamptz not null default now(),
  unique (access_control_item_id, action_label)
);
create index if not exists access_control_item_actions_item_id_idx on access_control_item_actions (access_control_item_id);
-- REVIEW REQUIRED: no code was found that cross-references
-- access_control_items/access_control_item_actions against
-- access_group_presets or users.page_permission_actions — how (or whether)
-- these two systems actually interact is unconfirmed.


-- ============================================================================
-- SECTION 6 — Organizational structure: active mapping system
-- (placed here, after users/system tables, because it has no dependents
-- among them — kept with the rest of org-structure conceptually, ordered
-- late only because org_mapping_levels -> org_custom_list_types already
-- exists by now)
-- ============================================================================

create table if not exists org_mapping_levels (
  id uuid primary key default gen_random_uuid(),
  list_type_id uuid not null unique references org_custom_list_types(id) on delete cascade,
  position integer not null,
  created_at timestamptz not null default now(),
  parent_level_id uuid references org_mapping_levels(id) on delete cascade,
  table_name text,
  mapping_columns text[]
);
create index if not exists org_mapping_levels_position_idx on org_mapping_levels (position);
create index if not exists org_mapping_levels_parent_idx on org_mapping_levels (parent_level_id);

-- Still actively used for root-level (no-parent) checkbox mappings; NOT
-- fully legacy despite most non-root levels having moved to org_map_<list>
-- tables (Section below). item_id has no FK constraint by design (it can
-- point at rows in many different list tables depending on level) — any
-- pre-migration Site uuid values stored here were NOT touched by the
-- sites-id migration and may now be unresolvable against the new integer
-- sites.id. REVIEW REQUIRED: audit this table's data if it's still relied on.
create table if not exists org_mapping_nodes (
  id uuid primary key default gen_random_uuid(),
  level_id uuid not null references org_mapping_levels(id) on delete cascade,
  item_id uuid not null,
  parent_node_id uuid references org_mapping_nodes(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (level_id, item_id, parent_node_id)
);
create index if not exists org_mapping_nodes_level_idx on org_mapping_nodes (level_id);
create index if not exists org_mapping_nodes_parent_idx on org_mapping_nodes (parent_node_id);

-- REVIEW REQUIRED: org_map_<list> tables (e.g. org_map_business_units,
-- org_map_departments, org_map_sections, org_map_custom_position, and one
-- per every other non-root mapping level an admin has configured) are the
-- CURRENT, live per-level mapping tables — but like custom_<slug> tables
-- above, the exact set that exists and each one's exact ancestor-chain
-- columns is runtime/admin-driven and cannot be listed as fixed CREATE
-- TABLE statements without inventing table names that may not match
-- reality. The shape every one of them follows:
--
--   create table org_map_<list> (
--     id uuid primary key default gen_random_uuid(),
--     <ancestor_1>_id <type> not null references <ancestor_1_table>(id) on delete cascade,
--     ... one FK column per level in the chain, root to self ...,
--     <self>_id <type> not null references <self_table>(id) on delete cascade,
--     created_at timestamptz not null default now(),
--     unique (<all chain columns>)
--   );
--
-- IMPORTANT: any such table whose chain includes Site now has an
-- `site_id integer` column (not uuid) — this was fixed at the generator-
-- function level (create_org_mapping_table now reads the referenced
-- table's actual id type instead of assuming uuid) as part of the sites
-- migration, so this applies automatically to every one of these tables,
-- present and future, without a table-by-table doc to go stale.
--
-- One confirmed special case: org_map_custom_age does not use a single
-- age_id column — per docs/organizational-structure/age-mapping-min-max.sql
-- it has age_min_id and age_max_id (both uuid, references custom_age(id)
-- on delete cascade) instead, alongside its normal ancestor chain.
--
-- To get the actual current set of these tables and their real columns,
-- query information_schema directly against the live database, or read
-- org_mapping_levels.table_name / mapping_columns per row.


-- ============================================================================
-- SECTION 7 — Task Manager
-- ============================================================================

create table if not exists tm_projects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  status text not null default 'active' check (status in ('active', 'archived')),
  created_by uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists tm_tasks (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references tm_projects(id) on delete cascade,
  title text not null,
  description text,
  owner_id uuid,                        -- REVIEW REQUIRED: references users.user_id conceptually, no DB-level FK constraint found
  start_date date,
  due_date date,
  is_recurring boolean not null default false,
  task_type text not null default 'general' check (task_type in ('general', 'obligation', 'monitoring')),
  frequency text,
  indicator text,
  method_provider text,
  lifecycle_status text not null default 'active' check (lifecycle_status in ('active', 'completed', 'archived', 'deleted')),
  completed_at timestamptz,
  progress_percent int not null default 0 check (progress_percent between 0 and 100),
  source text not null default 'manual' check (source in ('manual', 'ai_extracted')),
  source_document_url text,
  source_document_name text,
  created_by uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists tm_tasks_project_id_idx on tm_tasks (project_id);
create index if not exists tm_tasks_owner_id_idx on tm_tasks (owner_id);
create index if not exists tm_tasks_lifecycle_status_idx on tm_tasks (lifecycle_status);
create index if not exists tm_tasks_due_date_idx on tm_tasks (due_date);
-- NOTE: display_status (Not Started/In Progress/Overdue/Compliant-Ongoing/
-- Completed/Archived/Deleted) is NOT a stored column — computed at read time.

create table if not exists tm_subtasks (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references tm_tasks(id) on delete cascade,
  parent_id uuid references tm_subtasks(id) on delete cascade,
  title text not null,
  weight_percent int not null check (weight_percent between 0 and 100),
  is_done boolean not null default false,
  depth int not null check (depth between 1 and 4),
  position int not null default 0,
  owner_id uuid,                        -- REVIEW REQUIRED: same as tm_tasks.owner_id, conceptual FK to users.user_id only
  start_date date,
  due_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- NOTE: sibling weights summing to 100 is enforced only in application code, not a DB constraint.

create table if not exists tm_task_audit_log (
  id uuid primary key default gen_random_uuid(),          -- REVIEW REQUIRED: base column list beyond what's below not fully confirmed
  task_id uuid references tm_tasks(id) on delete set null, -- REVIEW REQUIRED: ON DELETE behavior assumed, not directly confirmed
  action text not null check (action in ('created', 'edited', 'archived', 'deleted', 'restored', 'completed')),
  performed_by uuid,
  created_at timestamptz not null default now()
);

create table if not exists tm_project_audit_log (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references tm_projects(id) on delete set null,
  action text not null check (action in ('created', 'renamed', 'archived', 'restored')),
  performed_by uuid,
  created_at timestamptz not null default now()
);

-- Deliberately has NO FK to tm_projects, so deletion history survives a
-- project's own cascade delete.
create table if not exists tm_project_deletions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null,
  project_name text,
  deleted_by uuid,
  created_at timestamptz not null default now()
);

create table if not exists tm_extraction_jobs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references tm_projects(id) on delete set null,
  file_name text,                       -- nullable per multi-document-extraction.sql
  file_url text,                        -- nullable per multi-document-extraction.sql
  files jsonb not null default '[]'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'completed', 'failed')),
  created_by uuid,
  created_at timestamptz not null default now()
);

create table if not exists tm_monthly_reports (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references tm_projects(id) on delete set null,
  stats_snapshot jsonb,
  generated_by uuid,                    -- nullable, since cron-generated reports have no human author
  created_at timestamptz not null default now()
);

create table if not exists tm_task_completions (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references tm_tasks(id) on delete cascade,
  project_id uuid references tm_projects(id) on delete cascade,
  completed_at timestamptz not null default now()
);

-- REVIEW REQUIRED: enforced as a singleton by application logic, not a DB
-- unique constraint — a real schema could theoretically hold >1 row.
create table if not exists tm_report_schedule (
  id uuid primary key default gen_random_uuid(),
  enabled boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists tm_reminder_settings (
  id uuid primary key default gen_random_uuid(),
  enabled boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists tm_reminder_log (
  id uuid primary key default gen_random_uuid(),
  task_id uuid references tm_tasks(id) on delete cascade,
  reminder_type text not null check (reminder_type in ('due_soon', 'overdue')),
  sent_on date not null,
  unique (task_id, reminder_type, sent_on)
);


-- ============================================================================
-- SECTION 8 — Recruitment / Job postings / Applications / Onboarding
-- (created before Leave/Appraisal/Promotion since users.application_id
-- above references job_applications, and appraisals/promotions don't
-- depend on these but keeping the recruitment chain together)
-- ============================================================================

create table if not exists job_postings (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  job_title_key text,
  title text not null,
  location text not null default 'Eastern Region, Ghana',
  employment_type text not null default 'Full-time',
  summary text not null,
  description text not null,
  interview_guide_key text not null default 'L1' check (interview_guide_key in (
    'L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'L7', 'consultant', 'data_analyst', 'veterinarian'
  )),
  jd_file_url text,
  jd_file_public_id text,
  closes_at timestamptz not null,
  status text not null default 'published' check (status in ('published', 'closed')),
  is_active boolean not null default true,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  superseded_by uuid references job_postings(id) on delete set null,
  history jsonb not null default '[]'::jsonb,
  role_scope text not null default '',
  key_responsibilities text not null default '',
  minimum_qualifications text not null default '',
  preferred_qualifications text not null default '',
  experience text not null default '',
  required_skills_attributes text not null default '',
  non_negotiable_standards text not null default '',
  archived_at timestamptz,
  optional_org_field_order jsonb default '[]'::jsonb,
  -- Dynamic org-placement FK columns, one per org-structure list, added at
  -- runtime by add_job_posting_org_column() — the 8 confirmed as backfilled
  -- when this feature launched:
  position_id uuid references custom_position(id) on delete set null,
  site_id integer references sites(id) on delete set null,             -- corrected: was uuid, migrated to integer this session
  business_unit_id uuid references business_units(id) on delete set null,
  age_id uuid references custom_age(id) on delete set null,
  salary_id uuid references custom_salary(id) on delete set null,
  department_id uuid references departments(id) on delete set null,
  section_id uuid references sections(id) on delete set null,
  grade_level_id uuid references grade_levels(id) on delete set null
  -- REVIEW REQUIRED: additional org-placement columns may exist beyond
  -- these 8 if more custom lists were added to job postings since —
  -- add_job_posting_org_column() runs per-list at admin configuration time,
  -- so the live set could be a superset of what's listed here.
);
create index if not exists job_postings_position_id_idx on job_postings (position_id);
create index if not exists job_postings_site_id_idx on job_postings (site_id);
create index if not exists job_postings_business_unit_id_idx on job_postings (business_unit_id);
create index if not exists job_postings_age_id_idx on job_postings (age_id);
create index if not exists job_postings_salary_id_idx on job_postings (salary_id);
create index if not exists job_postings_department_id_idx on job_postings (department_id);
create index if not exists job_postings_section_id_idx on job_postings (section_id);
create index if not exists job_postings_grade_level_id_idx on job_postings (grade_level_id);

create table if not exists job_applications (
  id uuid primary key default gen_random_uuid(),
  reference_number text not null unique,
  full_name text not null,
  email text not null,
  phone text not null,
  location text,
  role_slug text not null,
  role_title text not null,
  cover_note text,
  cv_url text,
  cv_public_id text,
  status text not null default 'applied' check (status in (
    'applied', 'under_review', 'shortlisted', 'interview', 'evaluation',
    'hold', 'onboarding', 'offer', 'rejected'
  )),
  hr_notes text,
  interview_form_data jsonb not null default '{}'::jsonb,
  interview_submitted_at timestamptz,
  interview_submitted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status_history jsonb not null default '[]'::jsonb,
  ai_screening jsonb,
  job_posting_id uuid references job_postings(id) on delete set null,
  application_form_data jsonb not null default '{}'::jsonb,
  submission_status text not null default 'submitted' check (submission_status in ('draft', 'submitted')),
  draft_token text unique,
  application_form_fields_snapshot jsonb
);

create table if not exists role_interview_reports (
  id uuid primary key default gen_random_uuid(),
  role_slug text,                        -- REVIEW REQUIRED: originally unique, that constraint was later dropped in favor of job_posting_id-based uniqueness — exact current uniqueness rule not fully confirmed
  role_title text not null,
  report jsonb not null,
  report_edit jsonb,
  report_edit_log jsonb not null default '[]'::jsonb,
  generated_at timestamptz,
  generated_by text,
  updated_at timestamptz,
  job_posting_id uuid references job_postings(id) on delete set null
);
-- REVIEW REQUIRED: exact partial unique index on job_posting_id not confirmed verbatim.

create table if not exists onboarding_tokens (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references job_applications(id) on delete cascade,
  token text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_sent_at timestamptz,
  revoked_at timestamptz
);

create table if not exists onboarding_submissions (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null unique references job_applications(id) on delete cascade,
  token_id uuid references onboarding_tokens(id) on delete set null,
  form_data jsonb not null default '{}'::jsonb,
  hr_data jsonb not null default '{}'::jsonb,
  personal_completed_at timestamptz,
  medical_completed_at timestamptz,
  referee_completed_at timestamptz,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists referee_reference_tokens (
  id uuid primary key default gen_random_uuid(),          -- REVIEW REQUIRED: base columns beyond referee_index assumed to mirror onboarding_tokens' shape, not independently confirmed
  application_id uuid not null references job_applications(id) on delete cascade,
  referee_index smallint not null check (referee_index between 1 and 5),
  token text not null unique,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists referee_reference_submissions (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references job_applications(id) on delete cascade,
  referee_index smallint not null check (referee_index between 1 and 5),
  form_data jsonb not null default '{}'::jsonb,           -- REVIEW REQUIRED: exact column name/shape not independently confirmed
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  unique (application_id, referee_index)
);


-- ============================================================================
-- SECTION 9 — Human Capital: Leave
-- ============================================================================

-- REVIEW REQUIRED: no SQL doc exists for the base table at all — fully
-- reconstructed from src/app/api/leave/apply/route.ts and
-- src/app/api/leave/review/route.ts. total_days' exact numeric type/
-- precision is not confirmed.
create table if not exists leave_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(user_id),
  leave_type text not null,                                -- values driven by system_options (mod:leave / leave.types), not a DB enum
  reason text,
  start_date date not null,
  end_date date not null,
  total_days numeric,                                        -- REVIEW REQUIRED: type inferred only
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  stage text not null default 'pending_supervisor' check (stage in (
    'pending_supervisor', 'pending_signoff', 'approved', 'rejected'
  )),
  document_url text,
  admin_note text,
  reviewed_by uuid references users(user_id),
  reviewed_at timestamptz,
  supervisor_reviewed_by uuid references users(user_id),
  supervisor_reviewed_at timestamptz,
  supervisor_note text,
  created_at timestamptz not null default now()
);
-- NOTE: `status` stays "pending" through both approval stages, only
-- flipping to approved/rejected on final resolution — status and stage are
-- deliberately redundant, per the two-stage-approval.sql migration comment.


-- ============================================================================
-- SECTION 10 — Human Capital: Appraisal
-- ============================================================================

create table if not exists appraisal_grade_templates (
  id uuid primary key default gen_random_uuid(),

  site_id integer not null references sites(id) on delete cascade,   -- corrected: was uuid, migrated to integer this session
  business_unit_id uuid not null references business_units(id) on delete cascade,
  department_id uuid not null references departments(id) on delete cascade,
  section_id uuid not null references sections(id) on delete cascade,
  position_id uuid not null references custom_position(id) on delete cascade,
  grade_level_id uuid not null references grade_levels(id) on delete cascade,

  quarterly_sections jsonb not null default '[]'::jsonb,
  annual_sections jsonb not null default '[]'::jsonb,
  extra_rules jsonb not null default '[]'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (site_id, business_unit_id, department_id, section_id, position_id, grade_level_id)
);
create index if not exists appraisal_grade_templates_lookup_idx on appraisal_grade_templates
  (site_id, business_unit_id, department_id, section_id, position_id, grade_level_id);

-- REVIEW REQUIRED: no SQL doc found for this table at all — fully
-- reconstructed from src/app/api/appraisal/** and src/lib/appraisal/server.ts.
-- status/locked_reason value sets are as OBSERVED in code, not necessarily
-- a real DB CHECK constraint — no such constraint was found in any doc, so
-- these may be plain `text` in the live database, enforced only in the app.
create table if not exists appraisals (
  id uuid primary key default gen_random_uuid(),
  company_id text not null,
  employee_name text not null,
  job_title text,
  current_grade text not null,
  section_authorisations_held text,
  immediate_supervisor text not null,
  supervisor_email text,
  employee_email text,
  cycle text,                                    -- 'quarterly' | 'annual', derived from review_quarter
  grade_band text not null,
  review_quarter text not null check (review_quarter in ('Q1', 'Q2', 'Q3', 'Q4')),
  review_year int not null,
  reviewing_manager text,
  period_covered text,
  promotion_readiness text,
  strengths_observed text,
  improvement_areas text,
  agreed_actions text,
  employee_comments text,
  most_significant_achievement text,
  development_plan_next_year text,
  promotion_readiness_assessment text,
  compensation_review_input text,
  employee_ratings jsonb,
  supervisor_ratings jsonb,
  employee_weighted_score numeric,
  supervisor_weighted_score numeric,
  employee_submitted_at timestamptz,
  supervisor_submitted_at timestamptz,
  supervisor_reviewed_by uuid,
  supervisor_reviewed_by_name text,
  submitted_by text default 'employee' check (submitted_by in ('employee', 'supervisor', 'both')),
  status text default 'open',                    -- REVIEW REQUIRED: values observed: 'open','submitted','final_reviewed','locked','reopened' — not confirmed as a real CHECK constraint
  deadline_at timestamptz,
  reopened_deadline_at timestamptz,
  employee_user_id uuid references users(user_id),
  supervisor_id uuid references users(user_id),
  final_review_date date,
  final_review_notes text,
  final_reviewed_by uuid,
  final_reviewed_by_name text,
  final_reviewed_at timestamptz,
  final_quarter_score numeric,
  employee_penalty_points numeric default 0,
  appeal_exhausted boolean default false,
  locked_reason text,                            -- REVIEW REQUIRED: values observed: 'employee_incomplete','supervisor_incomplete','reopen_incomplete'
  archived boolean default false,
  archived_at timestamptz,
  archived_by uuid,
  archived_by_name text,
  created_at timestamptz not null default now()
  -- REVIEW REQUIRED: no explicit unique constraint on (company_id,
  -- review_quarter, review_year) was found — "one appraisal per employee
  -- per cycle" appears to be enforced only in application code via
  -- upsert-by-select, not the database.
);

-- REVIEW REQUIRED: no SQL doc found — reconstructed from
-- src/app/api/appraisal/justification/route.ts and [id]/route.ts.
create table if not exists appraisal_justifications (
  id uuid primary key default gen_random_uuid(),
  appraisal_id uuid not null references appraisals(id),
  supervisor_id uuid not null references users(user_id),
  reason_text text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_by uuid,
  reviewed_by_name text,
  review_notes text,
  reviewed_at timestamptz,
  points_waived boolean,
  created_at timestamptz not null default now()
  -- REVIEW REQUIRED: "one justification per appraisal" enforced only in
  -- application code (a .maybeSingle() existence check), no DB unique
  -- constraint found.
);

-- REVIEW REQUIRED: no SQL doc found — reconstructed from
-- src/lib/appraisal/server.ts. id column's existence is assumed for
-- consistency with every other table, not directly observed in a select.
create table if not exists supervisor_penalties (
  id uuid primary key default gen_random_uuid(),
  supervisor_id uuid not null references users(user_id),
  appraisal_id uuid not null references appraisals(id),
  review_quarter text not null,
  review_year int not null,
  points_deducted numeric not null,
  waived boolean not null default false,
  justification_id uuid references appraisal_justifications(id)
);


-- ============================================================================
-- SECTION 11 — Human Capital: Skill Log
-- ============================================================================

create table if not exists skill_log_templates (
  id uuid primary key default gen_random_uuid(),
  site_id integer not null references sites(id) on delete cascade,   -- corrected: was uuid, migrated to integer this session
  business_unit_id uuid not null references business_units(id) on delete cascade,
  department_id uuid not null references departments(id) on delete cascade,
  section_id uuid not null references sections(id) on delete cascade,
  position_id uuid not null references custom_position(id) on delete cascade,
  grade_level_id uuid not null references grade_levels(id) on delete cascade,
  sections jsonb not null default '[]'::jsonb,
  tier_auth_options jsonb not null default '["None yet","GP","PS","External GGP semen handling"]'::jsonb,
  skill_variants jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (site_id, business_unit_id, department_id, section_id, position_id, grade_level_id)
);

-- REVIEW REQUIRED: no SQL doc found — reconstructed from
-- src/app/api/skillLog/create_skillLog/route.ts and [id]/route.ts. status
-- CHECK values beyond 'draft'/'signed_off' likely exist but weren't
-- directly observed. grade_level is deliberately NOT a stored column here
-- (confirmed by an explicit code comment) — always derived live via
-- users.grade_level_id.
create table if not exists skill_logs (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references users(user_id),
  supervisor_id uuid not null references users(user_id),
  log_type text not null,
  review_period text not null,
  section text,
  tier_auth text,
  strengths_observed text,
  development_gaps text,
  status text not null default 'draft',          -- REVIEW REQUIRED: only 'draft' and 'signed_off' directly observed; other in-progress values likely exist
  overall_rating numeric,
  signed_off_by uuid references users(user_id),
  signed_off_at timestamptz,
  created_at timestamptz not null default now()
);

-- REVIEW REQUIRED: no SQL doc found — id column assumed. observed/
-- performed_under_supervision/performed_consistently are read/written as
-- free strings by the API; may be constrained via CHECK in the live DB
-- (not confirmed either way).
create table if not exists skill_log_competencies (
  id uuid primary key default gen_random_uuid(),
  skill_log_id uuid not null references skill_logs(id) on delete cascade,
  skill text not null,
  observed text,
  performed_under_supervision text,
  performed_consistently text,
  rating numeric,
  comments text
);


-- ============================================================================
-- SECTION 12 — Human Capital: Promotion
-- ============================================================================

-- REVIEW REQUIRED: only 4 columns (promotion_step, time_in_current_role,
-- business_need_confirmed, form_data) are documented anywhere
-- (docs/CAREERS_RECRUITMENT_SUPABASE.md §5, an ALTER TABLE snippet, not a
-- full CREATE). Every other column below is reconstructed purely from
-- insert/select payloads in src/app/api/promotion/**. final_decision's
-- value set was never observed/enumerated anywhere in the code reviewed.
create table if not exists promotions (
  id uuid primary key default gen_random_uuid(),
  appraisal_id uuid not null references appraisals(id),
  employee_company_id text not null,
  employee_name text not null,
  current_grade text not null,
  current_job_title text,
  proposed_job_title text,
  proposed_grade text,
  immediate_supervisor text,
  reviewing_manager text,
  tier_authorisation text,
  section_unit text,
  triggering_review text,
  eligibility_checklist jsonb default '{}'::jsonb,
  assessment_ratings jsonb default '{}'::jsonb,
  final_decision text not null,                  -- REVIEW REQUIRED: value set never confirmed
  decision_comments text,
  conditions text,
  submitted_by_user_id uuid references users(user_id),
  submitted_by_grade text,
  promotion_step text,
  time_in_current_role text,
  business_need_confirmed boolean,
  form_data jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- NOTE: promotion eligibility itself is driven by users.final_score /
-- users.final_score_year / users.promotion_eligible (Section 3), not a
-- column on this table.


-- ============================================================================
-- SECTION 13 — SOP (Standard Operating Procedures)
-- ============================================================================

-- content.id is BIGINT, not uuid — an earlier doc
-- (docs/task-manager/supporting-tables.sql) assumed uuid, but a later fix
-- (docs/sop/sop-audit-log-fix-content-id-type.sql) confirms the live column
-- is actually bigint (discovered via failed inserts in production). Using
-- the corrected type here.
create table if not exists content (
  id bigint generated by default as identity primary key,   -- REVIEW REQUIRED: exact identity/sequence definition not confirmed, "bigint" itself is confirmed
  title text not null,
  category text not null,
  sub_category text,
  description text,
  cover_image_url text,
  video_url text,
  video_duration_minutes int,
  document_url text,
  document_read_minutes int,
  created_by uuid,
  created_at timestamptz not null default now(),
  archived_at timestamptz
);

create table if not exists sop_audit_log (
  id uuid primary key default gen_random_uuid(),
  content_id bigint not null,           -- deliberately NOT a FK, so history survives content row deletion
  content_title text not null,
  action text not null check (action in ('added', 'edited', 'archived', 'restored', 'deleted')),
  performed_by uuid not null,
  performed_by_name text not null,
  performed_at timestamptz not null default now()
);
create index if not exists sop_audit_content_id_idx on sop_audit_log (content_id);
create index if not exists sop_audit_performed_at_idx on sop_audit_log (performed_at desc);


-- ============================================================================
-- SECTION 14 — User Manual
-- ============================================================================

create table if not exists user_manual_versions (
  id uuid primary key default gen_random_uuid(),
  cloudinary_url text not null,
  cloudinary_public_id text,
  file_name text not null,
  file_size_bytes bigint,
  version_label text not null,
  version_notes text,
  uploaded_by uuid not null,            -- REVIEW REQUIRED: no FK constraint to users found despite the name
  uploaded_at timestamptz not null default now()
);
create index if not exists user_manual_versions_uploaded_at_idx on user_manual_versions (uploaded_at desc);


-- ============================================================================
-- Offer letters / Company branding — NO dedicated table. Stored inside
-- system_modules.business_logic (Section 4) under a companyBranding key
-- (logoUrl, logoPublicId, addressLines) for whichever module represents
-- offer-letter/recruitment settings. Not a schema gap — this is genuinely
-- how the feature persists data.
-- ============================================================================
